[package]
name = "lemon-mbl-game-data"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
lemon-mbl-utils = { path = "../utils" }
serde = { version = "1.0.215", features = ["derive"] }
serde_yaml = "0.9.34"
